# Generated by Django 3.2 on 2021-04-25 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20210425_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='buy',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='currency',
            name='sale',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
