# Generated by Django 3.2 on 2021-04-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20210425_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(1, 'MONO_BANK'), (2, 'VKURSE_DP_UA'), (3, 'YAHOO_FINANCE'), (4, 'PRIVAT_BANK')]),
        ),
    ]
